### ISSUE TITLE
with_resque recursive bug?

### ISSUE THREAD

**Issue by hansy** [leshill/resque_spec#113]
I have a job that, among doing other things, re-schedules itself for the future. So:

```ruby
class ReminderJob
  @queue = :queue_name
   
  def self.perform(*args) 
    # stuff
    Resque.enqueue_in(days, ReminderJob, args)
  end
end
```

To test the #process method in RSpec, I'm doing:

```ruby
describe ReminderJob do
  before { ResqueSpec.reset! }
  describe "#perform" do
    before do
      with_resque do
        Resque.enqueue(described_class, args)
      end

    # my tests go here
   end
end
```
I get a `stack level too deep` when running the tests. If I remove the re-scheduling part from the job, everything works fine. How can I work around this?

**Comment by leshill** [comment]
Hi @hansy,

Perhaps you might restructure the test to not use `with_resque` and instead do something like:

```ruby
describe ".perform" do
  it "does a thing" do
    ReminderJob.perform(args_go_here)
    expect(ReminderJob).to have_queued(expected_args_go_here)
  end
end

Does that help?

**Comment by hansy** [comment]
@leshill so simple. Yes, it does help. Thank you so much!
