### ISSUE TITLE
Resque.enqueue doesn't queue jobs when resque_spec is bundled

### ISSUE THREAD

**Issue by ngw** [leshill/resque_spec#7]
Hi *, I'm experiencing a superstrange problem where Resque.enqueue doesn't sort any effect (it doesn't even write on Redis) but calling Job directly does.

https://gist.github.com/869265

I honestly don't see how to give more detail than the code that works and the one that doesn't.
I'm using rails 2.0.5, rvm with ruby 1.9.2, and the latest vesion of resque.

**Comment by dpmccabe** [comment]
Why was this issue closed without a solution? I'm experiencing this same bug.

**Comment by leshill** [comment]
Hi @dpmccabe,

Take a look at the comments under the gist, it was resolved there.

**Comment by leshill** [comment]
Hi @dpmccabe,

If that resolves it for you, we can add a comment here for future reference.

**Comment by dpmccabe** [comment]
I think my problem is something else. I'll write up a different issue.
